
### get users

GET http://localhost:3000/users

### get users by id 
GET http://localhost:3000/users/3

### 

PATCH http://localhost:3000/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoidGh1bmRlcm1hbnMiLCJpYXQiOjE3MTM5NTQ4MzQsImV4cCI6MTcxMzk1NTczNH0._bzkq45qmlbUqeajgYgoePo67HZQTpOeGH0Y8pOyisg

    {
    "firstName": "racheal",
    "lastName": "vengwa",
    "password": "password"
  }

### Delete
DELETE  http://localhost:3000/users/200

###

POST  http://localhost:3000/auth/signup
Content-Type: application/json

    {"firstName":"arlonenyasha",
    "lastName": "vengwa",
    "userName": "thundermans",
    "password": "password"
  }

###
POST  http://localhost:3000/auth/signin
Content-Type: application/json


    {
    "userName": "thundermans",
    "password": "password"
  }
### 
GET http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoidGh1bmRlcm1hbnMiLCJpYXQiOjE3MTM5NTY4NzgsImV4cCI6MTcxMzk1Nzc3OH0.zeKTBlZulKdIe9t3_NQYkFsimWeEqAX81KF9rBgzEMg
###
GET  http://localhost:3000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoidGh1bmRlcm1hbnMiLCJpYXQiOjE3MTM5NTc2OTEsImV4cCI6MTcxNDU2MjQ5MX0.hkRpcOM84aJfBppPaHsmb2Yg2hcgn6eS9Ge491Hk7t8

