
### get users

GET http://localhost:3000/users

### get users by id 
GET http://localhost:3000/users/3

### 

PATCH http://localhost:3000/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjMsInVzZXJuYW1lIjoidGh1bmRlcm1hbnMiLCJpYXQiOjE3MTM5NTQ4MzQsImV4cCI6MTcxMzk1NTczNH0._bzkq45qmlbUqeajgYgoePo67HZQTpOeGH0Y8pOyisg

    {
    "firstName": "racheal",
    "lastName": "vengwa",
    "password": "password"
  }

### Delete
DELETE  http://localhost:3000/users/200

###

POST  http://localhost:3000/auth/signup
Content-Type: application/json

    {"firstName":"arlonenyasha",
    "lastName": "vengwa",
    "userName": "thundermans",
    "password": "password"
  }

###
POST  http://localhost:3000/auth/signin
Content-Type: application/json


    {
    "userName": "thundermans",
    "password": "password"
  }
### 
GET http://localhost:3000/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidGh1bmRlcm1hbnMiLCJpYXQiOjE3MTQ0OTQ4MTcsImV4cCI6MTcxNDQ5NTcxN30.cy4Y50F2bDGfQOVMoZms-yEoeSbvyIPt8DmyZQJX3EY
###
GET  http://localhost:3000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidGh1bmRlcm1hbnMiLCJpYXQiOjE3MTQ0OTQ4NjksImV4cCI6MTcxNTA5OTY2OX0.Ztlv4_vpLVhyIW9si5lxtxkXzbDZmAGIWsehsf85Uyk